# .pre-commit-config.yaml - terraform & HCL linting
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
      - id: terraform_fmt
        files: '\.(tf|tfvars|hcl)$'
      # - id: terraform_validate
      #   # files: '\.tf$'
      #   files: '^infra/modules/[^/]+/[^/]+\.tf$'
      - id: terraform_tflint
        files: '\.tf$'
        args:
        - --args=--disable-rule=terraform_required_providers
        - --args=--disable-rule=terraform_required_version