server:
  address: 'tcp://0.0.0.0:9091/'
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'

log:
  level: info

theme: auto

totp:
  issuer: homelab
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
  password_reset:
    disable: true  # if this is false, jwt secret is required

session:
  name: authelia_session
  same_site: lax
  inactivity: 1h
  expiration: 12h
  remember_me: 7d
  cookies:
    - domain: 'easontm.com'
      # <AUTHELIA_URL>
      authelia_url: 'https://auth.easontm.com'

storage:
  encryption_key: 'a_very_important_secret'
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: deny
  rules:
    # - domain: '192.168.1.72'
    #   policy: one_factor
    #   resources:
    #     - '^/nginx.*'
    - domain: "*.easontm.com"
      policy: one_factor

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 5m