postgres_password: ENC[AES256_GCM,data:Lep9LUwKYpYVRU7LHMHUE+ijAA==,iv:S7O0XW7y/28//kz72E4Ml8tMXLlBVLIOM1Y/5hDuPps=,tag:nF7bdabLcHVXovYH35WJUg==,type:str]
paperless_url: ENC[AES256_GCM,data:Ydi5GLJuL2clDlXToYN9NLLSLqB3re77Dvl7Aq8=,iv:Tnx9Ou0q+ALyiwY8QnJwhfCMCZVGpKri+f+IHpLs3To=,tag:FZs7yKZI5wvjmKLZiYIwsw==,type:str]
paperless_csrf_trusted_origins: ENC[AES256_GCM,data:55wYk9p/4jooT88PiUXGszbMaMgbABpVIgal4hg=,iv:/BbvQhui+iUCdpeuLIrv/Ugg1VsHvvmkFqro4QGKnO4=,tag:9xBx70ooMq1CFBt0sDRpog==,type:str]
sops:
    age:
        - recipient: age1cnf37e7jrmwth60a896enxu9vtu3j9r84c7lq4wdtdsvqnz43ymswhlrjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdzV1QVNKOUl4VS9BYmRB
            TUlOTDFlQTR1cWRlVjloTWxJNnZUWmkyVDNjCkV5UHlRSG5yd2JMRXNyc3dCZUtX
            Z2ZLd3hFNFlLS25aYVJYdGowbDQ1SEkKLS0tIGlPYkYreWQ0cUJ0d2NPRm9aa3Jl
            R3F6Ri9yU3d4UXhNV1F1QzNqNjJOUkkKFXNRiGQ0ojes96RCtNc+4FN6UNHHaiWz
            AZj10qVnKSZd7bVWleyfRcY0WA3ZXkAIP8jGedIB+AzCBVXIErGMsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T07:47:49Z"
    mac: ENC[AES256_GCM,data:Gok4CSwGzq3s5rVfX7GnpFDcJPYCgA2GgU28Y40nf4aM3a3VYC5fTZwXjmEQEJPXQa5j0c2hCxtP2ygXL8jpNYCx5y0UAd4Mj1ahVH8dwnn+6T414JHAcP2Ffh1UuUimwIRNu+RQifN4ylc50Mw4QajQn6LAqQ7AYDWMLxJgSuM=,iv:KmX+HTWHHfKumo6zZyf/S5GG3D5dinE141VaTlemUpQ=,tag:Bp5T7o9DFi7wLXNbAqb5Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
