apiVersion: v1
kind: Service
metadata:
  labels:
    app: paperless-ngx
    component: webserver
  name: webserver
spec:
  ports:
    - name: '8000'
      port: 8000
      targetPort: 8000
  selector:
    app: paperless-ngx
    component: webserver
